-- Seed the stable metric catalogue used by extraction and public data APIs.

INSERT INTO metrics (code, name, category, unit, description)
VALUES
    ('REVENUE', 'Revenue', 'GROWTH', 'EUR',
     'Revenue reported for the selected period.'),
    ('CUSTOMER_COUNT', 'Customer Count', 'GROWTH', 'COUNT',
     'Number of customers for the selected period and dimension.'),
    ('REVENUE_MIX', 'Revenue Mix', 'GROWTH', 'PERCENT',
     'Percentage of revenue attributed to a breakdown member.'),
    ('ACV', 'Annual Contract Value', 'GROWTH', 'EUR',
     'Annual contract value for the selected solution.'),
    ('PIPELINE_VALUE', 'Pipeline Value', 'GROWTH', 'EUR',
     'Sales pipeline value for the selected pipeline stage.'),
    ('PIPELINE_CUSTOMER_COUNT', 'Pipeline Customer Count', 'GROWTH', 'COUNT',
     'Number of customers represented in the sales pipeline.'),

    ('GROSS_PROFIT', 'Gross Profit', 'PROFITABILITY', 'EUR',
     'Gross profit reported for the selected period.'),
    ('GROSS_MARGIN', 'Gross Margin', 'PROFITABILITY', 'PERCENT',
     'Gross profit expressed as a percentage of revenue.'),
    ('OPERATING_LOSS', 'Operating Loss', 'PROFITABILITY', 'EUR',
     'Operating loss reported for the selected period.'),
    ('OPERATING_MARGIN', 'Operating Margin', 'PROFITABILITY', 'PERCENT',
     'Operating result expressed as a percentage of revenue.'),
    ('COST_OF_SALES', 'Cost of Sales', 'PROFITABILITY', 'EUR',
     'Cost of sales reported for the selected period.'),
    ('ADMINISTRATIVE_EXPENSES', 'Administrative Expenses', 'PROFITABILITY', 'EUR',
     'Administrative expenses reported for the selected period.'),
    ('RND_INTENSITY', 'R&D Intensity', 'PROFITABILITY', 'PERCENT',
     'Research and development intensity reported for the selected period.'),

    ('CASH_BALANCE', 'Cash Balance', 'LIQUIDITY', 'EUR',
     'Cash balance at the reported value date.'),
    ('OPERATING_CASH_FLOW', 'Operating Cash Flow', 'LIQUIDITY', 'EUR',
     'Net cash flow from operating activities for the selected period.'),
    ('FREE_CASH_FLOW', 'Free Cash Flow', 'LIQUIDITY', 'EUR',
     'Free cash flow for the selected period.'),
    ('WORKING_CAPITAL_MOVEMENT', 'Working Capital Movement', 'LIQUIDITY', 'EUR',
     'Movement in working capital for the selected period.'),
    ('CURRENT_ASSETS', 'Current Assets', 'LIQUIDITY', 'EUR',
     'Current assets at the reported value date.'),
    ('CURRENT_LIABILITIES', 'Current Liabilities', 'LIQUIDITY', 'EUR',
     'Current liabilities at the reported value date.'),
    ('NET_CURRENT_POSITION', 'Net Current Position', 'LIQUIDITY', 'EUR',
     'Net position derived from current assets and current liabilities.'),
    ('CAPITAL_EXPENDITURE', 'Capital Expenditure', 'LIQUIDITY', 'EUR',
     'Capital expenditure for the selected period.'),

    ('BANK_DEBT', 'Bank Debt', 'CAPITAL', 'EUR',
     'Outstanding bank debt at the reported value date.'),
    ('LOAN_MOVEMENT', 'Loan Movement', 'CAPITAL', 'EUR',
     'Movement in loan balances for the selected period.'),
    ('INTEREST_EXPENSE', 'Interest Expense', 'CAPITAL', 'EUR',
     'Interest expense reported for the selected period.'),
    ('EQUITY_FINANCING', 'Equity Financing', 'CAPITAL', 'EUR',
     'Equity financing raised during the selected period.'),
    ('NET_CASH', 'Net Cash', 'CAPITAL', 'EUR',
     'Net cash position at the reported value date.'),
    ('NET_ASSET_POSITION', 'Net Asset Position', 'CAPITAL', 'EUR',
     'Net asset position at the reported value date.'),
    ('CONTINGENT_CONSIDERATION', 'Contingent Consideration', 'CAPITAL', 'EUR',
     'Contingent consideration recognised at the reported value date.');

-- Seed scalar and breakdown dimension members defined by the database design.

INSERT INTO dimensions (dimension_type, code, label)
VALUES
    ('TOTAL', 'TOTAL', 'Total'),
    ('CUSTOMER_SEGMENT', 'ENTERPRISE', 'Enterprise'),
    ('CUSTOMER_SEGMENT', 'INDEPENDENT', 'Independent'),
    ('CUSTOMER_SEGMENT', 'RND', 'R&D'),
    ('SOLUTION', 'SOIL', 'Soil'),
    ('SOLUTION', 'TERRAIN', 'Terrain'),
    ('SOLUTION', 'ERA', 'ERA'),
    ('GEOGRAPHY', 'IRELAND', 'Ireland'),
    ('PIPELINE_STAGE', 'OPEN', 'Open'),
    ('PIPELINE_STAGE', 'CLOSED', 'Closed');
